export const data = [
  {
    id: 1,
    name: "Like Dandelion Dust",
    year: 1991,
    Author: "Addi Rusling",
  },
  {
    id: 2,
    name: "Piccadilly",
    year: 2009,
    Author: "Marlie Vanyashin",
  },
  {
    id: 3,
    name: "Terrorist, The (a.k.a. Malli) (Theeviravaathi)",
    year: 2007,
    Author: "Lilla Mohammed",
  },
  {
    id: 4,
    name: "Bleeder",
    year: 2002,
    Author: "Jesse Loughan",
  },
  {
    id: 5,
    name: "Pink Panther 2, The",
    year: 1991,
    Author: "Jeniffer Winmill",
  },
  {
    id: 6,
    name: "Here and Elsewhere",
    year: 2013,
    Author: "Sebastian Vennart",
  },
  {
    id: 7,
    name: "How to Deal",
    year: 1995,
    Author: "Pia Tenney",
  },
  {
    id: 8,
    name: "Horror Business",
    year: 1996,
    Author: "Sabrina Biddlecombe",
  },
  {
    id: 9,
    name: "Brothers of the Head",
    year: 2006,
    Author: "Kevan Debold",
  },
  {
    id: 10,
    name: "GasLand",
    year: 2004,
    Author: "Richie Kasper",
  },
  {
    id: 11,
    name: "Home Alone",
    year: 1992,
    Author: "Ray Sambedge",
  },
  {
    id: 12,
    name: "Mahakaal (The Monster)",
    year: 2000,
    Author: "Brendin Kollatsch",
  },
  {
    id: 13,
    name: "Bullet for Joey, A",
    year: 1995,
    Author: "Maddy Vanyukhin",
  },
  {
    id: 14,
    name: "Cat and the Canary, The",
    year: 2011,
    Author: "Inigo Edgeller",
  },
  {
    id: 15,
    name: "Find Me Guilty",
    year: 1995,
    Author: "Giacinta Lunck",
  },
  {
    id: 16,
    name: "Evening with Kevin Smith, An",
    year: 2012,
    Author: "Penrod Gerant",
  },
  {
    id: 17,
    name: "Space",
    year: 2005,
    Author: "Tori Drees",
  },
  {
    id: 18,
    name: "Dark at the Top of the Stairs, The",
    year: 2008,
    Author: "Dode Gribben",
  },
  {
    id: 19,
    name: "G.I. Joe: The Rise of Cobra",
    year: 2002,
    Author: "Joellyn Noel",
  },
  {
    id: 20,
    name: "Seducing Mr. Perfect",
    year: 2004,
    Author: "Elisa Breazeall",
  },
  {
    id: 21,
    name: "The Six Million Dollar Man",
    year: 1993,
    Author: "Monah Agnew",
  },
  {
    id: 22,
    name: "Woman Chaser, The",
    year: 2002,
    Author: "Sylvester Cowling",
  },
  {
    id: 23,
    name: "Blood and Wine (Blood & Wine)",
    year: 2011,
    Author: "Chicky Patrie",
  },
  {
    id: 24,
    name: "Hatchet for the Honeymoon (Rosso segno della follia, Il)",
    year: 1994,
    Author: "Winfred Forgie",
  },
  {
    id: 25,
    name: "Down to Earth",
    year: 2003,
    Author: "Gary Careswell",
  },
  {
    id: 26,
    name: "Inheritance, The (Karami-ai)",
    year: 1997,
    Author: "Penelope Lutz",
  },
  {
    id: 27,
    name: "I Know What You Did Last Summer",
    year: 1996,
    Author: "Idell Fazackerley",
  },
  {
    id: 28,
    name: "Prince of Foxes",
    year: 2008,
    Author: "Charlena Bettington",
  },
  {
    id: 29,
    name: "Lonesome Dove",
    year: 2005,
    Author: "Aron Prisley",
  },
  {
    id: 30,
    name: "Trash",
    year: 1993,
    Author: "Nealson Lambrick",
  },
  {
    id: 31,
    name: "Resident Evil: Degeneration (Baiohazâdo: Dijenerêshon)",
    year: 1992,
    Author: "Tibold De Fraine",
  },
  {
    id: 32,
    name: "Random Hearts",
    year: 1999,
    Author: "Riley Edgecumbe",
  },
  {
    id: 33,
    name: "Foreverland",
    year: 1993,
    Author: "Sanford Cantle",
  },
  {
    id: 34,
    name: "Aprile",
    year: 2012,
    Author: "Dulcine Osband",
  },
  {
    id: 35,
    name: "24 Exposures",
    year: 1996,
    Author: "Yettie Szymoni",
  },
  {
    id: 36,
    name: "Delusions of Grandeur (La folie des grandeurs)",
    year: 1999,
    Author: "Garland Dinneges",
  },
  {
    id: 37,
    name: "Land",
    year: 2009,
    Author: "Laurie Netley",
  },
  {
    id: 38,
    name: "Quest",
    year: 2012,
    Author: "Suki Rehme",
  },
  {
    id: 39,
    name: "Dog's Life, A",
    year: 2006,
    Author: "Amandi Allom",
  },
  {
    id: 40,
    name: "Sex Ed",
    year: 2003,
    Author: "Daniel Sine",
  },
  {
    id: 41,
    name: "Body Heat",
    year: 2003,
    Author: "Linus Sivewright",
  },
  {
    id: 42,
    name: "Dave Attell: Captain Miserable",
    year: 2009,
    Author: "Virgie Stanett",
  },
  {
    id: 43,
    name: "Raid on Rommel",
    year: 2004,
    Author: "Geoffrey Denyukin",
  },
  {
    id: 44,
    name: "Rite, The",
    year: 1990,
    Author: "Valerie Christoforou",
  },
  {
    id: 45,
    name: "Late Show, The",
    year: 2011,
    Author: "Nancee Swaysland",
  },
  {
    id: 46,
    name: "JFK",
    year: 1998,
    Author: "Annelise Molden",
  },
  {
    id: 47,
    name: "Five Minutes of Heaven",
    year: 2004,
    Author: "Isacco Allinson",
  },
  {
    id: 48,
    name: "Dolores Claiborne",
    year: 1988,
    Author: "Arvin Triplett",
  },
  {
    id: 49,
    name: "Wildcat, The (Die Bergkatze)",
    year: 2002,
    Author: "Freemon Renforth",
  },
  {
    id: 50,
    name: "Spider-Man: The Ultimate Villain Showdown",
    year: 2007,
    Author: "Kristien Ivens",
  },
  {
    id: 51,
    name: "Firm, The",
    year: 1992,
    Author: "Gan Gadsden",
  },
  {
    id: 52,
    name: "Peach Thief, The (Kradetzat na praskovi)",
    year: 1994,
    Author: "Davey Oggers",
  },
  {
    id: 53,
    name: "Of Gods and Men (Des hommes et des dieux)",
    year: 2008,
    Author: "Gallard McReidy",
  },
  {
    id: 54,
    name: "Bomber",
    year: 2010,
    Author: "Bria Cartan",
  },
  {
    id: 55,
    name: "Zombie Honeymoon",
    year: 2010,
    Author: "Tamarah Smalls",
  },
  {
    id: 56,
    name: "Playing with Love (Puppy Love) (Maladolescenza)",
    year: 2003,
    Author: "Sayres Battill",
  },
  {
    id: 57,
    name: "Pretty Village, Pretty Flame (Lepa sela lepo gore)",
    year: 2006,
    Author: "Pansie Rubery",
  },
  {
    id: 58,
    name: "Last Wave, The",
    year: 2003,
    Author: "Davidson Eggar",
  },
  {
    id: 59,
    name: "Act of Aggression",
    year: 2008,
    Author: "Fern Luther",
  },
  {
    id: 60,
    name: "Bitch Hug (Bitchkram)",
    year: 2000,
    Author: "Liana Cron",
  },
  {
    id: 61,
    name: "Ghost Machine",
    year: 1983,
    Author: "Mordy Bennison",
  },
  {
    id: 62,
    name: "Astronaut's Wife, The",
    year: 2005,
    Author: "Maxim Welland",
  },
  {
    id: 63,
    name: "Band Baaja Baaraat",
    year: 2010,
    Author: "Fredek Attle",
  },
  {
    id: 64,
    name: "Town, The",
    year: 1989,
    Author: "Ad Inman",
  },
  {
    id: 65,
    name: "Hi-Life",
    year: 1997,
    Author: "Lee Horrigan",
  },
  {
    id: 66,
    name: "Big Game",
    year: 2002,
    Author: "Carson McCutcheon",
  },
  {
    id: 67,
    name: "Cold Prey (Fritt Vilt)",
    year: 1997,
    Author: "Gelya Benedit",
  },
  {
    id: 68,
    name: "Altered States",
    year: 2010,
    Author: "Anjanette Shaefer",
  },
  {
    id: 69,
    name: "Where Are My Children?",
    year: 2001,
    Author: "Clarisse Steane",
  },
  {
    id: 70,
    name: "Manzanar Fishing Club, The",
    year: 2002,
    Author: "Ryon Pillans",
  },
  {
    id: 71,
    name: "Year My Parents Went on Vacation, The (O Ano em Que Meus Pais Saíram de Férias)",
    year: 2010,
    Author: "Marv O' Meara",
  },
  {
    id: 72,
    name: "Shampoo",
    year: 1997,
    Author: "Harman McCumesky",
  },
  {
    id: 73,
    name: "Only the Young",
    year: 1993,
    Author: "Leda Treneman",
  },
  {
    id: 74,
    name: "Behold a Pale Horse",
    year: 1993,
    Author: "Stormy Wychard",
  },
  {
    id: 75,
    name: "Lost Battalion, The",
    year: 2009,
    Author: "Aurora Holworth",
  },
  {
    id: 76,
    name: "Japanese Story",
    year: 2009,
    Author: "Gale DelaField",
  },
  {
    id: 77,
    name: "Once Around",
    year: 1977,
    Author: "Kennett Solland",
  },
  {
    id: 78,
    name: "Message in a Bottle",
    year: 1989,
    Author: "Jesse Hedworth",
  },
  {
    id: 79,
    name: "Driver, The",
    year: 2008,
    Author: "Kerr Jahndel",
  },
  {
    id: 80,
    name: "Dallas: War of the Ewings",
    year: 2006,
    Author: "Maurise Ephgrave",
  },
  {
    id: 81,
    name: "Across the Tracks",
    year: 2002,
    Author: "Felice Limpertz",
  },
  {
    id: 82,
    name: "36th Chamber of Shaolin, The (Shao Lin san shi liu fang) (Master Killer)",
    year: 1986,
    Author: "Rodrique Barthelme",
  },
  {
    id: 83,
    name: "City of No Limits, The (la ciudad sin límites, En)",
    year: 1986,
    Author: "Carin Blanket",
  },
  {
    id: 84,
    name: "Remote Control",
    year: 2004,
    Author: "Nicolai Clevely",
  },
  {
    id: 85,
    name: "Girl Model",
    year: 1993,
    Author: "Delano Ashby",
  },
  {
    id: 86,
    name: "Invisible Sign, An",
    year: 1995,
    Author: "Laryssa Prinn",
  },
  {
    id: 87,
    name: "Christmas on Mars",
    year: 1999,
    Author: "Bax Broadis",
  },
  {
    id: 88,
    name: "Margaret",
    year: 1988,
    Author: "Janelle Boleyn",
  },
  {
    id: 89,
    name: "Prophecy",
    year: 1992,
    Author: "Scottie McCall",
  },
  {
    id: 90,
    name: "Calloused Hands",
    year: 2011,
    Author: "Dannie Adamsen",
  },
  {
    id: 91,
    name: "Something Like Happiness (Stestí)",
    year: 2009,
    Author: "Giorgio McWhirter",
  },
  {
    id: 92,
    name: "Brother Rat",
    year: 2004,
    Author: "Rolph Greasty",
  },
  {
    id: 93,
    name: "Breath, The (Nefes: Vatan sagolsun)",
    year: 1999,
    Author: "Raddy Thrustle",
  },
  {
    id: 94,
    name: "Adventures of Baron Munchausen, The",
    year: 2007,
    Author: "Prue Grunwald",
  },
  {
    id: 95,
    name: "Swamp Thing",
    year: 1985,
    Author: "Rolph Davitti",
  },
  {
    id: 96,
    name: "I.Q.",
    year: 1990,
    Author: "Ashton Tompsett",
  },
  {
    id: 97,
    name: "Min så kallade pappa",
    year: 1964,
    Author: "Suki Grane",
  },
  {
    id: 98,
    name: "Inevitable Defeat of Mister & Pete, The",
    year: 1997,
    Author: "Neddy Drache",
  },
  {
    id: 99,
    name: "Auntie Mame",
    year: 1990,
    Author: "Rosalinde Heathfield",
  },
  {
    id: 100,
    name: "Valley Of Flowers",
    year: 1995,
    Author: "Francoise Spoure",
  },
];
